/** Page titles shared by the topbar, the document title and page headers. */
export const PAGE_TITLES: Record<string, string> = {
  "/": "Overview",
  "/code": "Code",
  "/packages": "Packages",
  "/console": "Console",
  "/details": "Details",
  "/permissions": "Permissions",
  "/listing": "Listing",
  "/dashboard": "Dashboard",
  "/storefront": "Storefront",
  "/api": "API routes",
  "/jobs": "Jobs",
  "/hooks": "Hooks",
  "/data": "Store data",
  "/email": "Email outbox",
  "/realtime": "Realtime",
  "/ship": "Validate & publish",
  "/settings": "Project settings",
  "/user-settings": "User settings",
}
